// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dthuzmzwmhqyqquclfgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0aHV6bXp3bWhxeXFxdWNsZmd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5OTQ1NzgsImV4cCI6MjA3MjU3MDU3OH0.6O91IV6NMycptkqYGieu4iZson_SUu_wORDUQFQIPz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});